steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud container clusters get-credentials test-cluster --zone
        us-central1-a --project cloudside-academy  
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - builds
      - submit
      - '--region=us-central1'
      - '--tag'
      - >-
        us-central1-docker.pkg.dev/cloudside-academy/sudhakar-test/test-image:$BUILD_ID
    id: Build-Docker-Image
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - gcloud container images describe us-central1-docker.pkg.dev/cloudside-academy/sudhakar-test/test-image:$_TAG --format 'value(image_summary.digest)' > sha
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - gcloud container binauthz create-signature-payload --artifact-url=us-central1-docker.pkg.dev/cloudside-academy/sudhakar-test/test-image@$(awk 'NR==1{print $1}' sha) > ./generated_payload.json
      - openssl dgst -sha256 -sign ./ec_private.pem ./generated_payload.json > ./ec_signature
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - gcloud container binauthz attestations create --project="$_PROJECT_ID" --artifact-url="us-central1-docker.pkg.dev/cloudside-academy/sudhakar-test/test-image@$(awk 'NR==1{print $1}' sha)" --attestor=projects/cloudside-academy/attestors/"$_ATTESTOR_NAME" --signature-file=./ec_signature --public-key-id=$$DEMO --validate
      secretEnv: ['DEMO']
  availableSecrets:
      secretManager:
      - versionName: projects/769170094354/secrets/DEMO/versions/1
        env: 'DEMO'
  
