steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud container clusters get-credentials test-cluster --zone
        us-central1-a --project cloudside-academy  
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - builds
      - submit
      - '--region=us-central1'
      - '--tag'
      - >-
        us-central1-docker.pkg.dev/cloudside-academy/sudhakar-test/test-image:$BUILD_ID
    id: Build-Docker-Image
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        sh demo.sh
    entrypoint: bash
