steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud container clusters get-credentials test-cluster --zone
        us-central1-a --project cloudside-academy  
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - builds
      - submit
      - '--region=us-central1'
      - '--tag'
      - >-
        us-central1-docker.pkg.dev/cloudside-academy/sudhakar-test/test-image:$BUILD_ID
    id: Build-Docker-Image
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - gcloud container images describe us-central1-docker.pkg.dev/cloudside-academy/sudhakar-test/test-image:$_TAG --format 'value(image_summary.digest)' > sha
    entrypoint: bash
  - name: bash
    args:
      - '-c'
      - export DIGEST=$(awk 'NR==1{print $1}' sha)
      - echo $DIGEST
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - gcloud container binauthz create-signature-payload 
        --artifact-url=us-central1-docker.pkg.dev/cloudside-academy/sudhakar-test/test-image@$_DIGEST > ./generated_payload.json
    entrypoint: bash
