name: Build and Deploy to GKE DEV

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: cloudside-academy
  GKE_CLUSTER: sudhakar-test
  GKE_ZONE: us-central1-c
  REPO_NAME: sudhakar-test
  IMAGE: github-action-test
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: Installing packages
        run: |-
          gcloud components install gke-gcloud-auth-plugin 
        
      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
      - name: Get GKE Credentials
        env :
          USE_GCLOUD_AUTH_PLUGIN: true
        run: |-
          gcloud container clusters get-credentials sudhakar-test --zone us-central1-c --project cloudside-academy
      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$(git rev-parse --short "$GITHUB_SHA")" .
      - name: Publish Docker Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$(git rev-parse --short "$GITHUB_SHA")"
      - name: push image tag to env repo
        env:
          PAT: ${{secrets.PAT}}
        run: |-
          git clone https://${PAT}@github.com/sudhakar678/github-action-gke.git
          cd github-action-gke
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo the new image tag will be $git_hash
          tag=$(cat deployment.yaml | grep 'gcr.io/cloudside-academy/github-action-test:' | awk -F: '{print $0=$3}')
          echo the old image tag is $tag
          sed -i 's/'"${tag}"'/'"${git_hash}"'/' deployment.yaml
          git config --global user.name "sudhakar678"
          git config --global user.email "sudhadhakar88@gmail.com"
          git remote set-url origin https://sudhakar678:${PAT}@github.com/sudhakar678/github-action-gke.git
          git add deployment.yaml
          git commit -m "image version updated in deployment file"
          git push
          echo the new image tag $git_hash is updated
